appid: BOT_ACCESS_TOKEN
homeserver: matrix-client.matrix.org
max_links: 3
min_image_width: 475
max_image_embed: 300
no_results_react: 💨
url_blacklist:
 - "192.168.1.1"
 - "1.0.0.0/8"
 - "10.0.0.0/8"
 - "172.16.0.0/12"
 - "192.168.0.0/16"
 - "fc00::/7"
 - "3fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
 - "2001:800::/21"
